main_app/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/edit_profile/', views.UserEditView.as_view(), name = 'edit_profile'),
    path('accounts/add_profilepic/', views.add_profilepic, name='add_profilepic'),
    path('spirits/', views.SpiritList.as_view(), name='spirits_index'),
    path('spirits/create/',views.SpiritCreate.as_view(), name='spirits_create'),
    path('spirits/<int:pk>/', views.SpiritDetail.as_view(), name='spirits_detail'),
    path('spirits/<int:pk>/update/', views.SpiritUpdate.as_view(), name='spirits_update'),
    path('spirits/<int:pk>/delete/', views.SpiritDelete.as_view(), name='spirits_delete'),
    path('wingedlight/', views.WingedLightList.as_view(), name='wingedlight_index'),
    path('wingedlight/<int:pk>/', views.WingedLightDetail.as_view(), name='wingedlight_detail'),
    path('wingedlight/create/', views.WingedLightCreate.as_view(), name='wingedlight_create'),
    path('wingedlight/<int:pk>/update/', views.WingedLightUpdate.as_view(), name='wingedlight_update'),
    path('wingedlight/<int:pk>/delete/', views.WingedLightDelete.as_view(), name='wingedlight_delete'),
]

skycotl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(null = True, upload_to = 'images/profile')
    pic_url = models.CharField(null = True, max_length=250)
    
    def get_absolute_url(self):
        return reverse('edit_profile')
    
    
    def __str__(self):
        return f'{self.user.username}: {self.user.first_name} {self.user.last_name}'
    
class ProfilePic(models.Model):
    url = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'Photo url for {self.user_id} @ {self.url}'
    
SPIRITS = (
    ('Candlemaker', 'Candlemaker'),
    ('Stargazer', 'Stargazer'),
    ('Voyager', 'Voyager'),
    ('Charmer', 'Charmer'),
    ('Bellmaker', 'Bellmaker'),    
)

class Spirit(models.Model):
    tag = models.CharField(null=True, max_length=20)
    name = models.CharField(max_length=100)
    realm = models.CharField(max_length=100)
    url = models.CharField(max_length=200)   
    
    def __str__(self):
        return f'{self.id} - {self.tag}'
    
    class Meta:
        ordering = ['name']
        

class UserSpirit(models.Model):
    tag = models.CharField(
        null=True,
        max_length=20,
        choices=SPIRITS,
        default=SPIRITS[0][0],
        )
    name = models.CharField(max_length=100)
    realm = models.CharField(max_length=100)
    url = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True, max_length= 500)
    user = models.ManyToManyField(User)
    
    def __str__(self):
        return f'{self.id} - {self.tag}'
    
    def get_absolute_url(self):
        return reverse('spirits_detail', kwargs={'pk': self.id})
    
REALMS = (
    ('Isle of Dawn', 'Isle'),
    ('Daylight Prairie', 'Daylight'),
    ('Hidden Forest', 'Forest'),
    ('Valley of Triump', 'Valley'),
    ('Golden Wasteland', 'Wasteland'),
    ('Vault of Knowledge', 'Vault'),
    ('Secret Area', 'Secret'),
)

class WingedLight(models.Model):
    wingedlight = models.IntegerField(null=True)
    realm = models.CharField(
        max_length=20,
        choices=REALMS,
        default=REALMS[0][0]
        )
    location = RichTextField()
    url = models.CharField(null=True,blank=True,max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.id} - {self.realm}'
    
    class Meta:
            ordering = ['realm']
    
    def get_absolute_url(self):
        return reverse('wingedlight_detail', kwargs={'pk': self.id})

main_app/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import Profile, UserSpirit, WingedLight
from django.forms import ModelForm
from django import forms


class SignUpForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')
        
class EditProfileForm(UserChangeForm):
        
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
        
class SpiritForm(ModelForm):
    class Meta:
        model = UserSpirit
        fields = ['description', 'name']
        
# class AddWingedLightForm(forms.ModelForm):
#     class Meta:
#         model = WingedLight
#         fields = ('wingedlight','realm','location')
    
    

main_app/views.py
from ast import Del
from hashlib import new
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
import boto3, uuid
from .forms import SignUpForm, EditProfileForm, SpiritForm
from.models import Profile, ProfilePic, Spirit, UserSpirit, User, WingedLight
from django.urls import reverse_lazy, reverse
import psycopg2

S3_BASE_URL = 'https://s3-us-east-2.amazonaws.com/'
BUCKET = 'sky-cotl-cj'


# Create your views here.
def home(request):
    return render(request, 'home.html')

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request, user)
            return redirect('home')
        else:
            error_message = 'Invalid sign up - try again'
    # request.method == 'GET'
    form = SignUpForm()
    context = {'form': form, 'error_message': error_message}            
    return render(request, 'registration/signup.html', context)

class UserEditView(LoginRequiredMixin, UpdateView):
    form_class = EditProfileForm
    template_name = 'registration/edit_profile.html'
    
    def get_object(self):
        return self.request.user
    
    success_url = reverse_lazy('edit_profile')
    
@login_required 
def add_profilepic(request):
    # check to see if there is an instance of the model Profile
    # if not save an instance of profile linked to the active user making the request        
    if not(Profile.objects.filter(user = request.user).exists()):
            Profile(user = request.user).save()
    print(request.user.profile)
    
    # add file to s3 bucket with authentic url
    photo_file = request.FILES.get('photo-file', None)
    print('user id: ',request.user.id, photo_file)
    if photo_file:
        session = boto3.Session(profile_name='sky')
        s3_client = session.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]        
        s3_client.upload_fileobj(photo_file, BUCKET, key)
        # build full url string
        user_profile = Profile(user = request.user)
        url  = f'{S3_BASE_URL}{BUCKET}/{key}'
        
        
        connection = psycopg2.connect(  user="contactharrisc2",
                                        password="J0s3aRr901",
                                        host="localhost",
                                        port="5432",
                                        database="sky_cotl")
        cursor = connection.cursor()
        print("Table Before updating record: ")
        sql_select_query = """select * from main_app_profile where user_id = %s"""
        cursor.execute(sql_select_query, (request.user.id,))
        record = cursor.fetchone()
        print(record)
        
        #Update single record now
        sql_update_query = """Update main_app_profile set pic_url = %s where user_id = %s"""
        cursor.execute(sql_update_query, (url, request.user.id))
        connection.commit()
        count = cursor.rowcount
        print(count, "Record Updated successfully")
        
        print("Table After updating record ")
        sql_select_query = """select * from main_app_profile where user_id = %s"""
        cursor.execute(sql_select_query, (request.user.id,))
        record = cursor.fetchone()
        print(record)
        
        # closing database connection
        if connection:
            cursor.close()
            connection.close()
            print("PostgreSQL connection is closed")
    return redirect('edit_profile')


@login_required
def add_screenshot(request):
    spirit_data = ""
    blank_form = SpiritForm()
    form = SpiritForm(request.POST)
    if form.is_valid():
        new_spirit = form.save(commit=False)
        spirit_data = Spirit.objects.filter(name = new_spirit.name)
        new_spirit.user_id = request.user_id
        new_spirit.realm = spirit_data.realm
        new_spirit.url = spirit_data.url
    return render(request, "add_spirit.html", {
        'spirit_form': blank_form,
    })

class SpiritCreate(LoginRequiredMixin, CreateView):
    model = UserSpirit
    fields = ['tag', 'description']
    def form_valid(self, form):
        user_spirit = form.instance
        # user_spirit = self.object
        # user_spirit= form.save(commit=False)
        user_spirit.save()
        user_spirit.user.add(self.request.user)
        data_spirit = Spirit.objects.get(tag=user_spirit.tag)
        user_spirit.name = data_spirit.name
        user_spirit.realm = data_spirit.realm
        user_spirit.url = data_spirit.url
        user_spirit.save()
                
        # user_spirit = Spirit.objects.get(user = self.request.user)
        # data_spirit = Spirit.objects.get(tag = user_spirit.tag)
        # user_spirit.name = data_spirit.name
        # user_spirit.realm = data_spirit.realm
        # user_spirit.url = data_spirit.url
        # user_spirit.set()
        return super().form_valid(form)

class SpiritList(LoginRequiredMixin, ListView):
    model = UserSpirit 

class SpiritDetail(LoginRequiredMixin, DetailView):
    model = UserSpirit
    success_url = reverse_lazy('/spirits/')
    
class SpiritUpdate(LoginRequiredMixin, UpdateView):
    model = UserSpirit
    fields = ['description']
    
class SpiritDelete(LoginRequiredMixin, DeleteView):
    model = UserSpirit
    success_url = reverse_lazy('spirits_index')
    
class WingedLightList(LoginRequiredMixin, ListView):
    model = WingedLight

class WingedLightDetail(LoginRequiredMixin, DetailView):
    model = WingedLight
    success_url = '/wingedlight/'
    
class WingedLightCreate(LoginRequiredMixin, CreateView):
    model = WingedLight
    fields= ['wingedlight', 'realm', 'location']
    
    def form_valid(self, form):
        new_wingedlight = form.instance
        new_wingedlight.user_id = self.request.user.pk
        new_wingedlight.save()
        photo_file = self.request.FILES.get('photo-file', None)
        
        if photo_file:
            session = boto3.Session(profile_name='sky')
            s3_client = session.client('s3')
            key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]        
            s3_client.upload_fileobj(photo_file, BUCKET, key)
            # build full url string
            url  = f'{S3_BASE_URL}{BUCKET}/{key}'
            new_wingedlight.url = url
        return super().form_valid(form) 
    success_url = '/wingedlight/'
    

class WingedLightUpdate(LoginRequiredMixin, UpdateView):
    model = WingedLight
    fields = ['realm', 'location']

class WingedLightDelete(LoginRequiredMixin, DeleteView):
    model = WingedLight
    success_url = '/wingedlight/'

main_app/templates/main_app/userspirit_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
        <h1>Delete Spirit</h1>
        <br>
        <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>
        <form action="" method="POST">
            {% csrf_token %}
            <input type="submit" value="Yes - Delete!" class="btn btn-outline-primary rounded-pill">
            <a href="{% url 'spirits_detail' userspirit.id %}" class="btn btn-outline-primary rounded-pill">Cancel</a>
        </form>
        
    </div>
{% endblock %}

main_app/templates/main_app/userspirit_detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <h1>Spirit:</h1>
    </div>

    <br>

    <div class="row">
        <div class="col s6 col-offset-3">
            <div class="container">
                <div class="card-content">
                    <span class="card-title"><h3>{{ userspirit.name }}</h3></span>                    
                    <img src="{{ userspirit.url }}" alt="">
                    <p>Description: {{ userspirit.description }}</p>
                </div>       
                <div class="container">
                    <a href="{% url 'spirits_update' userspirit.id %}" class="btn btn-outline-primary rounded-pill">Edit</a>
                    <a href="{% url 'spirits_delete' userspirit.id %}" class="btn btn-outline-primary rounded-pill">Delete</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

main_app/templates/main_app/userspirit_form.html
{% extends 'base.html' %}    

{% block content %}


  <div class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-outline-primary rounded-pill" value="Add Spirit">
      </form>
  </div>

    <!-- <script>
      const selectEl = document.getElementById('id_name');

      //Configure the select tag
      M.FormSelect.init(selectEl);
    </script> -->

{% endblock %}

main_app/templates/main_app/userspirit_list.html
{% extends 'base.html' %}

{% block content %}

    <style>
        /* .center{
            display: flex;
            justify-content: center;
        } */
    </style>

    <div class="container">
        <h1 class="title">My Spirits</h1>
        <br>

        {% if user.userspirit_set.count == 0 %}
            <h3>Rescue some Spirits!</h3>
        {% endif %}
    </div>

    {% for spirit in userspirit_list %}
        
        <div class="container center">
            <div class="card-content">
                <a href=" {% url 'spirits_detail' spirit.id %}">
                    <span class="card-title" style="display: block;">{{ spirit.name }}</span>                    
                    <img src="{{ spirit.url }}" alt="spirit photo"/>
                </a>       
                <h3>Realm: {{ spirit.realm }}</h3>
                <p>Description: {{ spirit.description }}</p>
            </div>
        </div>        
        <hr>

    {% endfor %}


{% endblock %}

main_app/templates/main_app/wingedlight_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>Delete Winged Light</h1>
    <br>
    <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span></h4>
    
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!" class="btn btn-outline-primary rounded-pill">
        <a href="{% url 'wingedlight_detail' object.id %}" class="btn btn-outline-primary rounded-pill">Cancel</a>
    </form>
</div>
    
{% endblock %}

main_app/templates/main_app/wingedlight_detail.html
{% extends 'base.html' %}

{% block content %}
<style>
    .center{
        display: flex;
        justify-content: center;
    }
</style>
    <br>
    <h1 class="title">Winged Light</h1>
    <br>

    <div class="center">
        <div class="card-content">
            <h3 class="card-title">{{ wingedlight.realm }}</h3>
            <img src="{{ wingedlight.url }}" alt="winged light location">
            <p>location: {{ wingedlight.location}}</p>
        </div>       
        <div class="card-action">
            <a href="{% url 'wingedlight_update' wingedlight.id %}" class="btn btn-outline-primary rounded-pill">Edit</a>
            <a href="{% url 'wingedlight_delete' wingedlight.id %}" class="btn btn-outline-primary rounded-pill">Delete</a>
        </div>
    </div>
    
{% endblock %}

main_app/templates/main_app/wingedlight_form.html
{% extends 'base.html' %}
<!-- string following 'block' must match the string following block in base.html -->
{% block content %}

    <div class="container">
        {% if object %}
            <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
        {% else %}
            <h1>Add Winged Light</h1>
        {% endif %}
         <!-- Leaving the action empty makes the form post to the same url used to display it -->
         <form action="" method="POST" enctype="multipart/form-data">
            <!-- Django requires the csrf token for security purposes -->
            {% csrf_token %}
            
            <br><br>
            <table>
                <!-- Render the inputs inside of <tr>s & <td>s -->
                {{ form.as_table }}
        
            </table>
            <input type="file" name="photo-file">
            <br><br>
            <input type="submit" value="Submit!" class="btn btn-outline-primary rounded-pill">
         </form>
    </div>


{% endblock %}

main_app/templates/main_app/wingedlight_list.html
{% extends 'base.html' %}
<!-- the string following block must match the same string in base.thml
for django to inject html in that position -->
<!-- The html code will only be inject if the user hits the route/path -->
{% block content %}
<!-- all html and python code is written between the blocks -->
<style>
    .center{
        display: flex;
        justify-content: center;
    }

    .de-link{
        text-decoration: none;
        color: inherit;
    }
</style>

{% if user.wingedlight_set.count == 0 %}
    <div class="container">
        <h1 class="title">Seek Adventures to Fly Higher!</h1>
    </div>
{% else %}
    <div class="container">
        <h1 id ="title-text" class="title">Winged Light:</h1>
    </div>
{% endif %}


{% for wingedlight in wingedlight_list %}
    <a href="{% url 'wingedlight_detail' wingedlight.id %}" class="de-link">
        <div class="container center">
            <div class="card-content">
                <span class="card-title"><h1 class="center">{{ wingedlight.wingedlight }}</h1></span>
                <h3>Realm: {{ wingedlight.realm }}</h3>
                {% if wingedlight.url %}
                    <img src="{{ wingedlight.url }}" alt="winged light screenshot"/>
                    <p>Location: {{ wingedlight.location }}</p>
                {% endif %}
            </div>
        </div>
    </a>
    <hr>
{% endfor %}

{% endblock %}